DEV:
  db_type: "postgres"
  host: "database-1-instance-1.cl7vxsat3hqn.us-east-1.rds.amazonaws.com"
  port: 5432
  user: "postgres"
  password: "Zaq12wsx"
  database: "my_test_db"
  pooling:
    minconn: 1
    maxconn: 5

PROD:
  db_type: "postgres"
  host: "prod-db.yourcompany.com"
  port: 5432
  user: "prod_user"
  password: "prod_password"
  database: "prod_db"
  pooling:
    minconn: 2
    maxconn: 10

DEV_S3:
  db_type: "s3"
  region: "us-east-1"