DEV:
  db_type: "postgres"
  host: "database-1-instance-1.cl7vxsat3hqn.us-east-1.rds.amazonaws.com"
  port: 5432
  user: "postgres"
  password: "Zaq12wsx"
  database: "my_test_db"
  pooling:
    minconn: 1
    maxconn: 5
  # Optionally these new fields:
  iam_auth: False  # or true if you want to use IAM
  region: "us-east-1"
  sslrootcert: "rds-ca-2019-root.pem"
  sslmode: "require"
  token_ttl: 900

PROD:
  db_type: "postgres"
  host: "prod-db.yourcompany.com"
  port: 5432
  user: "prod_user"
  password: "prod_password"
  database: "prod_db"
  pooling:
    minconn: 2
    maxconn: 10

DEV_S3:
  db_type: "s3"
  region: "us-east-1"

  ############################################################
  # NEW: Oracle Dev environment example
  ############################################################
  DEV_ORACLE:
    db_type: "oracle" # If using user/password:
    dsn: "dev-oracle.company.com"
    port: 1521
    service_name: "ORCLDEV"     # or 'sid' if you have a SID
    user: ""
    password: ""
    pooling:
      min: 1
      max: 5
      increment: 1
    # If using Kerberos, you might set these:
    use_kerberos: True         # set to true if OS-level Kerberos auth
    external_auth: True        # if Kerberos, typically true in your code

  ############################################################
  # NEW: Oracle Prod environment example
  ############################################################
  PROD_ORACLE:
    db_type: "oracle" # If using user/password:
    dsn: "dev-oracle.company.com"
    port: 1521
    service_name: "ORCLDEV"     # or 'sid' if you have a SID
    user: ""
    password: ""
    pooling:
      min: 1
      max: 5
      increment: 1
    # If using Kerberos, you might set these:
    use_kerberos: True         # set to true if OS-level Kerberos auth
    external_auth: True        # if Kerberos, typically true in your code

